# backend-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  - host: api.votredomaine.com # REMPLACER par votre domaine
    http:
      paths:
      - path: /api/ # Toutes les requÃªtes vers /api/
        pathType: Prefix
        backend:
          service:
            name: django-backend-service # Nom du service backend
            port:
              number: 8000