apiVersion: v1
kind: Secret
metadata:
  name: woyofalxamxam-secrets
  namespace: woyofalxamxam
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # base64: admin123
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTRsYjJeMi1edyVzMSlzbCg2M241MWVhcm1AenpxZWR1c204amEmd191d0Bpb2o5NjF0  # base64 encoded